name = "Serials Hugo base theme"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"

[author]
  name = "NYU Digital Libraries Technology Services"
  homepage = "//dlib.nyu.edu/dlts/"

